default_language_version:
    python: python3

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-added-large-files
    args: ['--maxkb=2000']
  - id: debug-statements
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.4
  hooks:
  - id: ruff
    args: [--select, I, --fix]
  - id: ruff-format
